### ISSUE TITLE
Unable to properly update version

### ISSUE THREAD

**Issue by VigorousManiac** [aws-solutions/quota-monitor-for-aws#147]
When attempting to deploy the hub template to our specific account I am getting 2 errors that looks to be canceling the rest of the install. For reference I have the 6.0.0 template currently installed for the hub and the prerequisite template and our spoke accounts are both at the newest templates of 6.2.1. The following errors received are "Resource handler returned message: ""StackSet QM-TA-Spoke-StackSet:b97e8fb5-c8e3-46e8-9abf-22674672e0cb not found (Service: CloudFormation, Status Code: 404, Request ID: 94164bcb-4694-4196-95dc-3b3004c927c6)" (RequestToken: 32318852-0a89-ed32-d70e-a408c11be434, HandlerErrorCode: GeneralServiceException)"" and  ""Resource handler returned message: "StackSet QM-SQ-Spoke-StackSet:49a5e0f1-7e9b-48dc-a482-c2ead7f4ab5b not found (Service: CloudFormation, Status Code: 404, Request ID: db0a8768-b59e-441a-8825-a04ddc035b1b)" (RequestToken: d287cb55-a57b-7735-0a1a-ac25e9e9663a, HandlerErrorCode: GeneralServiceException)"". From what I understand it seems like it is looking for pre-existing stacksets named those specific names. However I didnt think that was needed.

**Comment by abe-aws** [comment]
Hello,
It seems that you are deploying in [organizations mode](https://docs.aws.amazon.com/solutions/latest/quota-monitor-for-aws/step-1.-choose-your-deployment-scenario.html). In that mode, you don't have to manually deploy the spoke stacks, the stackset instances in the member accounts are automatically deployed when you add/edit the organization in the [parameter store](https://docs.aws.amazon.com/solutions/latest/quota-monitor-for-aws/step-4b.-update-systems-manager-parameter-store-ous.html). 

Since quota monitoring doesn't depend on history, you cad delete the existing stacks and deploy as new. Delete the stack instances in the member accounts and then the hub stack.

**Comment by VigorousManiac** [comment]
I deployed the spoke accounts from my hub account using stacksets. Are you saying this is not needed? If not then is all I need to do is delete the spoke stackset as well as the existing hub and then just redeploy the hub stack?

**Comment by abe-aws** [comment]
Yes, delete the existing hub and spoke stacks. After you deploy the hub as new, set set the organization id or organization unit id in [parameter store](https://docs.aws.amazon.com/solutions/latest/quota-monitor-for-aws/step-4b.-update-systems-manager-parameter-store-ous.html). The stackset instances will be created in a few minutes.

**Comment by VigorousManiac** [comment]
Will this allow me to deploy spokes only to specifically specified accounts in the organization and not all of them.

**Comment by VigorousManiac** [comment]
For reference the accounts I need to deploy spokes to are in different OUs under the main umbrella OU of the organization

**Comment by abe-aws** [comment]
Yes, you can specify a comma separated list of OU Ids.

**Comment by VigorousManiac** [comment]
i dont want all accounts within each OU. i have 3 accounts I want it in. All inside of seperate OUs, each of those OU also have other accounts in them that i dont want it deploy to.

**Comment by VigorousManiac** [comment]
This solved my issue. Thank you for the help.
