### ISSUE TITLE
How to test Quota Monitor once deployed

### ISSUE THREAD

**Issue by tyler-lemke-vu** [aws-solutions/quota-monitor-for-aws#202]
**What were you initially searching for in the docs?**
How to test that the Quota Monitor is working once deployed

**Is this related to an existing part of the documentation? Please share a link**
No

**Describe how we could make it clearer**
It would be nice to have specific steps that lay out how to test the service, especially a method to test it that doesn't involve spending more money to saturate the quotas

**If you have a proposed update, please share it here**
One way might be to provide low quota limits that the service can be switched to temporarily to help during the testing phase. This is more of a feature request than documentation but that is one approach that might work.

**Comment by G-Lenz** [comment]
Hi,

We have planned our next release and plan on including something similar in the next release, our plan is slightly different in that we were going to provide a method to simulate a test event so that it can be confirmed that the system, including the notification process works, this would make it so that arbitrary resources don't need to be created, and as you said, money does not need to be spent, in order to test that the solution works. We do not have an exact date for the release at the moment but will keep you up to date as best we can.
